// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxlmPyiYHtkDjWeHPbWfjG5cgZd9_pN4',
    appId: '1:208006271869:android:35517675edc0bb554d3214',
    messagingSenderId: '208006271869',
    projectId: 'queme-f9d7f',
    storageBucket: 'queme-f9d7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTv86hSOfAbBMQ3k1-pB8aszls1YYdlQ',
    appId: '1:208006271869:ios:7d896fed823795cd4d3214',
    messagingSenderId: '208006271869',
    projectId: 'queme-f9d7f',
    storageBucket: 'queme-f9d7f.appspot.com',
    iosBundleId: 'com.example.queme',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3EuUd0ADNha38CKeZVQ_KTFVkx2iYmzk',
    appId: '1:208006271869:web:20336fa6aef166d64d3214',
    messagingSenderId: '208006271869',
    projectId: 'queme-f9d7f',
    authDomain: 'queme-f9d7f.firebaseapp.com',
    storageBucket: 'queme-f9d7f.appspot.com',
    measurementId: 'G-5MQHXNBP9L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGTv86hSOfAbBMQ3k1-pB8aszls1YYdlQ',
    appId: '1:208006271869:ios:7d896fed823795cd4d3214',
    messagingSenderId: '208006271869',
    projectId: 'queme-f9d7f',
    storageBucket: 'queme-f9d7f.appspot.com',
    iosBundleId: 'com.example.queme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3EuUd0ADNha38CKeZVQ_KTFVkx2iYmzk',
    appId: '1:208006271869:web:f7c3b97bd233ddc74d3214',
    messagingSenderId: '208006271869',
    projectId: 'queme-f9d7f',
    authDomain: 'queme-f9d7f.firebaseapp.com',
    storageBucket: 'queme-f9d7f.appspot.com',
    measurementId: 'G-WJ4ZQMEN5Q',
  );

}